#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : R-rmeta
Version  : 3.0
Release  : 1
URL      : https://cran.r-project.org/src/contrib/rmeta_3.0.tar.gz
Source0  : https://cran.r-project.org/src/contrib/rmeta_3.0.tar.gz
Summary  : Meta-Analysis
Group    : Development/Tools
License  : GPL-2.0
BuildRequires : buildreq-R

%description
meta-analysis for two-sample comparisons and cumulative
        meta-analyses. Draws standard summary plots, funnel plots, and
        computes summaries and tests for association and heterogeneity.

%prep
%setup -q -c -n rmeta

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1584116418

%install
export SOURCE_DATE_EPOCH=1584116418
rm -rf %{buildroot}
export LANG=C.UTF-8
export CFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FCFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -flto -fno-semantic-interposition "
export AR=gcc-ar
export RANLIB=gcc-ranlib
export LDFLAGS="$LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=haswell -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library rmeta
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=skylake-avx512 -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=skylake-avx512 -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=skylake-avx512 -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --no-test-load --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library rmeta
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library rmeta
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc rmeta || :


%files
%defattr(-,root,root,-)
/usr/lib64/R/library/rmeta/DESCRIPTION
/usr/lib64/R/library/rmeta/INDEX
/usr/lib64/R/library/rmeta/Meta/Rd.rds
/usr/lib64/R/library/rmeta/Meta/data.rds
/usr/lib64/R/library/rmeta/Meta/features.rds
/usr/lib64/R/library/rmeta/Meta/hsearch.rds
/usr/lib64/R/library/rmeta/Meta/links.rds
/usr/lib64/R/library/rmeta/Meta/nsInfo.rds
/usr/lib64/R/library/rmeta/Meta/package.rds
/usr/lib64/R/library/rmeta/NAMESPACE
/usr/lib64/R/library/rmeta/R/rmeta
/usr/lib64/R/library/rmeta/R/rmeta.rdb
/usr/lib64/R/library/rmeta/R/rmeta.rdx
/usr/lib64/R/library/rmeta/data/catheter.rda
/usr/lib64/R/library/rmeta/data/cochrane.rda
/usr/lib64/R/library/rmeta/help/AnIndex
/usr/lib64/R/library/rmeta/help/aliases.rds
/usr/lib64/R/library/rmeta/help/paths.rds
/usr/lib64/R/library/rmeta/help/rmeta.rdb
/usr/lib64/R/library/rmeta/help/rmeta.rdx
/usr/lib64/R/library/rmeta/html/00Index.html
/usr/lib64/R/library/rmeta/html/R.css
